"""add plan to users

Revision ID: 294dae952dc1
Revises: 52dfc05bede5
Create Date: 2026-01-11 06:01:56.866126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294dae952dc1'
down_revision: Union[str, Sequence[str], None] = '52dfc05bede5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'restaurant_id')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
