"""add subscription plan to restaurants

Revision ID: cda354bc609a
Revises: b73dd781eb1d
Create Date: 2026-01-02 10:18:33.182835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda354bc609a'
down_revision: Union[str, Sequence[str], None] = 'b73dd781eb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('plan', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_restaurants_plan'), 'restaurants', ['plan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_plan'), table_name='restaurants')
    op.drop_column('restaurants', 'plan')
    # ### end Alembic commands ###
